### PR TITLE
list bs-platform as dev dependency

### PR DESCRIPTION
**Pull request by bobzhang**

### CODE REVIEW

**Comment by chenglou** [comment]
What do you think the future convention should be? devDep/dep/peerDep? Let's standardize it so that people don't do all sorts of things.

Why not dep though? It's not clear that the published JS artifacts can reliably or should be consumed by JS.

**Comment by bobzhang** [comment]
This is what I have in mind: so if it is devDependency, then `npm install rehydrate-example` would not cause `bs-platform` be built, for advanced users, I can run `npm link bs-platform`, for normal users, they can still run `npm install` inside the repo.

I think both devDep/peerDep looks good, maybe `peerDe` is better, if people want to just publish JS files, they can create a new npm package, like `rehydrate-example-js`

**Comment by jordwalke** [comment]
What's the goal here? Since we're not publishing artifacts, I think you normally want to either list `bs-platform` as a regular dep, or alternatively as (peerDep + devDep). Listing as peerDep + devDep ensures that *someone* installs `bs-platform`, and that this package will "see" it as a dependency when accessed via various tools like npm's `resolve()` (because it's listed as peerDep).

**Comment by chenglou** [comment]
Ok, for the sake of consistency with reason-react I did this. But let's not forget to come back to this discussion.

**Pull request closed without merging**
