### PR TITLE
switch to qnd and update readme.

### PR DESCRIPTION
**Pull request by kennetpostigo**
Switching to qnd makes setting up the examples easier for newcomers. One build command npm run start. 

Last night people came in asking what port the project was on, how do we view the examples, wheres the server running? It took a bit of time explaining how to view the examples. This should make it easier on them because it will start a dev server at `localhost:8000`.

### CODE REVIEW

**Comment by turadg** [comment]
This does look easier for newcomers.

With a fresh checkout though `npm start` outputs the following:
```
…
[6/10] Building src/todomvc/todoItem.cmj /Users/turadg/Code/ReasonML/qnd-reason-react-example/lib/es6/src/todomvc/todoItem.js src/todomvc/todoItem.cmi
[7/10] Building src/logo/logo.cmj /Users/turadg/Code/ReasonML/qnd-reason-react-example/lib/es6/src/logo/logo.js src/logo/logo.cmi
FAILED: src/logo/logo.cmj /Users/turadg/Code/ReasonML/qnd-reason-react-example/lib/es6/src/logo/logo.js src/logo/logo.cmi
/Users/turadg/Code/ReasonML/qnd-reason-react-example/node_modules/bs-platform/bin/bsc.exe -bs-package-name reason-react-example  -bs-package-output es6:lib/es6/src/logo -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include -I /Users/turadg/Code/ReasonML/qnd-reason-react-example/node_modules/reason-react/lib/ocaml -I /Users/turadg/Code/ReasonML/qnd-reason-react-example/node_modules/reason-js/lib/ocaml -I src/interop -I src/logo -I src/simple -I src/todomvc -I src  -nostdlib -I /Users/turadg/Code/ReasonML/qnd-reason-react-example/node_modules/bs-platform/lib/ocaml -no-alias-deps -color always -w -40+6+7+27+32..39+44+45 -o src/logo/logo.mlast -c  src/logo/logo.mlast
File "/Users/turadg/Code/ReasonML/qnd-reason-react-example/src/logo/logo.re", line 70, characters 12-251:
Error: This expression has type
         < WebkitUserSelect : string; color : string; fontFamily : string;
           fontSize : string; paddingTop : string; textAlign : string >
         Js.t
       but an expression was expected of type ReactDOMRe.style
[8/10] Building src/todomvc/app.cmj /Users/turadg/Code/ReasonML/qnd-reason-react-example/lib/es6/src/todomvc/app.js src/todomvc/app.cmi
ninja: build stopped: subcommand failed.
```

**Comment by kennetpostigo** [comment]
@turadg I didn't get this error will test again in a little bit, however this may be related to the recently added typed styles object. @chenglou is this related to style object https://github.com/reasonml/reason-react/pull/45?

**Comment by chenglou** [comment]
@turadg oops, you got caught between two releases. Wipe node_modules and things should work again.

**Comment by turadg** [comment]
Hmm, I tried that and got new errors. :-|

https://gist.github.com/turadg/0574734d8f3d46c0c2e5fc7200b65119

If it's a version matching issue, would a `yarn.lock` help?

**Comment by chenglou** [comment]
Yes, that's the same error. You can fix them like this: https://github.com/chenglou/reason-react-example/commit/c8bad27e8a7a4e6e6d35d86b1f8bca70b11d7507

I can rebase this PR later.

**Comment by chenglou** [comment]
@turadg also, join discord.gg/reasonml if you'd like =)
We provide almost real-time support there

**Comment by kennetpostigo** [comment]
@turadg were you unblocked?

**Comment by kennetpostigo** [comment]
Don't merge this. Will make a new PR with several changes.

**Pull request closed without merging**
