### PR TITLE
Simple grammatical change

### PR DESCRIPTION
**Pull request by Tetheta**
Just made me twitch is all. Not important.

### CODE REVIEW

**Comment by jordwalke** [comment]
I had to do a double take, but the existing grammar is correct (either that or I am misunderstanding the meaning of the original comment). This isn't attempting to say "**You are** familiar handleClick from ReactJS". It's attempting to say "(this is) your familiar handleClick from ReactJS". Maybe the lack of leading (this is) would have clarified?

**Comment by Tetheta** [comment]
Ah! I knew there was something I was missing. I was somehow mentally adding a "with" in there (You are familiar with handleClick) which still sounded odd but I didn't want to make a bigger change.
This is would have helped me a lot.

**Comment by Tetheta** [comment]
Ah! I knew there was something I was missing, brain must be getting tired. I was somehow mentally adding a "with" in there (You are familiar with handleClick) which still sounded odd but I didn't want to make a bigger change.
This is would have helped me a lot.
Is there a way to squash commits online on github?

**Comment by jordwalke** [comment]
The accepter squashes at time of merging (which I've just done). Thanks!

**Pull request merged**
